
services:
  order-service:
    build: ./OrderService/OrderService
    container_name: order-service
    ports:
      - "8082:8082"
    depends_on:
      - inventory-service
    networks:
      - micro-net

  inventory-service:
    build: ./InventoryService/InventoryService
    container_name: inventory-service
    ports:
      - "8081:8081"
    networks:
      - micro-net

  transactions-service:
    build: ./Transactions/Transactions
    container_name: transactions-service
    ports:
      - "8083:8083"
    depends_on:
      - order-service
    networks:
      - micro-net

networks:
  micro-net:
    driver: bridge
