spring.application.name=Transactions
spring.datasource.url = jdbc:mysql://host.docker.internal:3306/transactionsdb
spring.datasource.username = transuser
spring.datasource.password = transpass
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
server.port=8083
